### ISSUE TITLE
A search over the test names would be useful

### ISSUE THREAD

**Issue by ovatsus** [LambdaFactory/Neptune-public#12]
On large projects it's hard to find a specific test, a simplified search functionality, similar to what the VS Test Explorer does, would be useful

**Comment by Krzysztof-Cieslak** [comment]
I've thought about it, but due to limitations of the extensibilty of VSCode UI I cannot just put text box above the test tree that would be used for filtering or anything like that. 

The only solution is showing typical VSCode input box and using it for filtering, but I think that UX in such case wouldn't be too good (especially for something like quick searching), IMO.

**Comment by ovatsus** [comment]
I think even that would be useful

**Comment by Krzysztof-Cieslak** [comment]
`1.1.0` is adding `Go to test` command to command palette which can be used as quick search / navigation

**Comment by ovatsus** [comment]
Cool! Could you maybe put a button with a spyglass on the Text Explorer panel to invoke that?

**Comment by Krzysztof-Cieslak** [comment]
I've added it in `1.1.3`

![capture](https://user-images.githubusercontent.com/5427083/38768841-e96ce46a-3ff9-11e8-9fee-5097891a1a45.PNG)

**Comment by ovatsus** [comment]
Thanks!
